# Use root/example as user/password credentials
version: '3.1'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

  portal-demo:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.data.rest.base-path" : "/api",
        "spring.mvc.pathmatch.matching-strategy" : "ant_path_matcher",
        "spring.datasource.initialization-mode" : "always"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: