version: "3"
services:
  springboot-docker-portal-demo:
    image: ismjaffri96/springbootmysql	
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-net
    depends_on:
      - mysqldb
 
  mysqldb:
    image: ismjaffri96/mysql
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
    command: mysqld --init-file="/tmp/database/init.sql"
    networks:
      - springboot-mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=sa  

networks:
  springboot-mysql-net: 